lamp:
  authentication:
    # jwt 签名，长度至少32位。 建议每个公司都修改一下这个字符串
    jwtSignKey: 'lamp-cloud_is_a_fantastic_project'
  log:
    enabled: false
  webmvc:
    undertow: false
    header: false
  ignore:
    # 是否启用网关的 uri权限鉴权 (设置为false，则后台不校验访问权限)
    authEnabled: true
    # 前端校验按钮 是否区分大小写
    caseSensitive: false  
    anyone:       # 请求中 需要携带Tenant 且 需要携带Token(需要登录)，但不需要验证uri权限
      ALL:
        - /**/anyone/**
        - /activiti/service/model/*/json
        - /activiti/service/model/*/save
        - /activiti/service/editor/stencilset
    anyUser:      # 请求中 需要携带Tenant，但 不需要携带Token(不需要登录) 和 不需要验证uri权限
      ALL:
        - /**/anyUser/**
    anyTenant:    # 请求中 不需要携带Tenant 且 不需要携带Token(不需要登录) 和 不需要验证uri权限
      ALL:
        - /**/anyTenant/**        
spring:
  autoconfigure:
    exclude: io.seata.integration.http.HttpAutoConfiguration,org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  cloud:
    gateway:
      x-forwarded:
        prefixEnabled: false
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        # 新建服务配置复制到中间
        # 新建服务配置复制到中间
        - id: oauth
          uri: lb://lamp-oauth-server
          predicates:
            - Path=/oauth/**
          filters:
            - StripPrefix=1
        - id: system
          uri: lb://lamp-system-server
          predicates:
            - Path=/system/**
          filters:
            - StripPrefix=1
        - id: base
          uri: lb://lamp-base-server
          predicates:
            - Path=/base/**
          filters:
            - StripPrefix=1
        # websocket
        - id: wsMsg
          uri: lb:ws://lamp-base-server
          predicates:
            - Path=/wsMsg/**
          filters:
            - StripPrefix=1    
        - id: generator
          uri: lb://lamp-generator-server
          predicates:
            - Path=/generator/**
          filters:
            - StripPrefix=1            
        - id: activiti
          uri: lb://lamp-activiti-server
          predicates:
            - Path=/activiti/**
          filters:
            - StripPrefix=1


server:
  port: 18760
  servlet:
    context-path: /api
